version: "2.4"

services:
  web-db:
    image: mysql:5.6
    container_name: web-db
    mem_limit: 2G
    mem_reservation: 2G
    ports:
      - "3010:3010"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=supersecret
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d/
      - ./docker/mysql/datadir:/var/lib/mysql 
    command: "--default-authentication-plugin=mysql_native_password --lower_case_table_names=1 --character-set-server=utf8 --bind-address 0.0.0.0 --port 3010"
    healthcheck:
          test: "/etc/init.d/mysql status -P3310"
          interval: 2s
          retries: 10
